### ISSUE TITLE
Event detection in backend: store in DB and it's parameters

### ISSUE THREAD

**Issue by mrlori** [miguel-martinr/DeepView#6]
Detección  y almacenamiento de eventos.

**Comment by miguel-martinr** [comment]
En [60935c3](https://github.com/miguel-martinr/DeepView/commit/60935c3b1552c9b79d52a03837ebc4bad71e3007) :

* Se almacenan los parámetros para la detección de eventos (minArea) en la colección `deepcom_processingparametersmodel`
* Se guardan los eventos detectados: se guarda en qué segundos se ha detectado un evento en la colección `deepcom_videomodel`
